name: Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install asciidoctor
        run: |
          gem install asciidoctor
          gem install --pre asciidoctor-pdf
          asciidoctor -v
          asciidoctor-pdf -v

      - name: Build
        run: |
          sed -i -- 's/0.1.0/0.1.'$GITHUB_RUN_NUMBER'/g' src/index.adoc
          sed -i -- 's/0.1.0/0.1.'$GITHUB_RUN_NUMBER'/g' src/index-es.adoc
          sed -i -- 's/0.1.0/0.1.'$GITHUB_RUN_NUMBER'/g' src/index-fil.adoc
          cat src/index.adoc
          make

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: build
